apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front-container
          image: 809694441839.dkr.ecr.us-east-1.amazonaws.com/innovatech-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_ENDPOINT
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
valueFrom:
  secretKeyRef:
    name: db-credentials
    key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
type: ClusterIP
